# Tutorial on the usage of RSA tool

This tutorial illsutrates how to use the RSA tool on proteins. This tutorial is divided into two parts. The first part shows how to edit a protein structure file so that the RSA tool can be ran. The second part is the running of the RSA tool.

Before starting any analysis, load the neccesary modules for this class.

In [1]:

from pysoftk.pol_analysis.tools.utils_mda import MDA_input
from pysoftk.pol_analysis.tools.utils_tools import *
from pysoftk.pol_analysis.make_micelle_whole import micelle_whole
from pysoftk.pol_analysis.ring_ring import RSA

import numpy as np
import pandas as pd
import MDAnalysis as mda

/home/raquellrdc/.local/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


## 1. Editing the protein structure file

Load the initial trajectory

In [2]:
topology='data/protein_rsa_noedit.pdb'

trajectory='data/trajectory_rsa_protein.xtc'

u=mda.Universe(topology, trajectory)

In [3]:
u.trajectory[0].time

150000.0

Now, we need to make sure that each protein can be identified by a unique resid. That is to say, all atoms of the same protein must have the same resid, and this resid must be different to the resid of other proteins in the system. The following code shows how this can be achieved:

In [3]:
proteins_len=len(u.atoms)
protein_pos=u.atoms.positions
proteins=u.select_atoms('protein')

proteins.positions=protein_pos


#this is a manual way to select the proteins of a system, you need to adapt this code to your own system 
protein_1=u.select_atoms('segid A')
protein_2=u.select_atoms('segid B')
protein_3=u.select_atoms('segid C')
protein_4=u.select_atoms('segid D')
protein_5=u.select_atoms('segid E')
protein_6=u.select_atoms('segid F')
protein_7=u.select_atoms('segid G')
protein_8=u.select_atoms('segid H')
protein_9=u.select_atoms('segid I')
protein_10=u.select_atoms('segid J')


protein_1_len=len(np.unique(protein_1.resids))
protein_2_len=len(np.unique(protein_2.resids))
protein_3_len=len(np.unique(protein_3.resids))
protein_4_len=len(np.unique(protein_4.resids))
protein_5_len=len(np.unique(protein_5.resids))
protein_6_len=len(np.unique(protein_6.resids))
protein_7_len=len(np.unique(protein_7.resids))
protein_8_len=len(np.unique(protein_8.resids))
protein_9_len=len(np.unique(protein_9.resids))
protein_10_len=len(np.unique(protein_10.resids))

print(protein_1_len)




resids=[]


resids= resids + [1]*protein_1_len
resids= resids + [2]*protein_2_len
resids= resids + [3]*protein_3_len

resids= resids + [4]*protein_4_len
resids= resids + [5]*protein_5_len
resids= resids + [6]*protein_6_len

resids= resids + [7]*protein_7_len
resids= resids + [8]*protein_8_len
resids= resids + [9]*protein_9_len

resids= resids + [10]*protein_10_len



print(len(resids))
print(len(proteins))

proteins.residues.resids=resids

with mda.Writer("data/trajectory_resids.pdb", proteins.n_atoms) as W:
    
    W.write(proteins)

31
310
3270


Great, now the new structure file has been created, so that each protein has a unique resid for all of its atoms. Now we can run the RSA tool on this new file.

## 2.Running RSA 

With the new structure file, we can run the RSA tool in the exact same way we run it on polymers

In [4]:

topology='data/trajectory_resids.pdb'

trajectory='data/trajectory_rsa_protein.xtc'

In [5]:
#name output file
results='data/rsa_prot_tutorial.parquet'

#angle cutoff - angle range (val < ang_c or val> 180-ang_c). 
ang_c=30


#distance cutoff - distance between two rings to be considered stacked
dist_c=5



In [6]:
rsa=RSA(topology, trajectory).stacking_analysis(dist_c, ang_c, 0, 20, 2, results)

Ring Stacking analysis has started


Separating Rings: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 26/26 [00:00<00:00, 11647.11it/s]




Preparing DataFrame to store the results


 10%|█████████████████▍                                                                                                                                                            | 1/10 [00:08<01:17,  8.61s/it]

([(array([740, 741, 744, 746, 749]), array([1171, 1172, 1174, 1176, 1179, 1181]))], [(array([2173, 2174, 2177, 2179, 2182]), array([2411, 2413, 2403, 2404, 2406, 2408]))], [(array([2482, 2484, 2487, 2489, 2479, 2480]), array([2833, 2836, 2827, 2828, 2831])), (array([2500, 2501, 2504, 2506, 2509]), array([2706, 2708, 2711, 2702, 2703]))])



 20%|██████████████████████████████████▊                                                                                                                                           | 2/10 [00:16<01:06,  8.31s/it]

([(array([86, 87, 90, 92, 95]), array([544, 547, 538, 539, 542]))], [(array([193, 195, 198, 200, 190, 191]), array([871, 874, 865, 866, 869]))], [(array([211, 212, 215, 217, 220]), array([1171, 1172, 1174, 1176, 1179, 1181]))], [(array([740, 741, 744, 746, 749]), array([1171, 1172, 1174, 1176, 1179, 1181]))], [(array([1192, 1193, 1196, 1198, 1201]), array([1852, 1855, 1846, 1847, 1850]))], [(array([1749, 1750, 1752, 1754, 1757, 1759]), array([3133, 3134, 3136, 3138, 3141, 3143]))], [(array([2482, 2484, 2487, 2489, 2479, 2480]), array([2833, 2836, 2827, 2828, 2831]))], [(array([2809, 2811, 2814, 2816, 2806, 2807]), array([3065, 3067, 3057, 3058, 3060, 3062]))])



 30%|████████████████████████████████████████████████████▏                                                                                                                         | 3/10 [00:25<01:00,  8.67s/it]

([(array([86, 87, 90, 92, 95]), array([544, 547, 538, 539, 542]))], [(array([740, 741, 744, 746, 749]), array([1171, 1172, 1174, 1176, 1179, 1181]))], [(array([847, 849, 852, 854, 844, 845]), array([1498, 1499, 1501, 1503, 1506, 1508]))], [(array([1067, 1068, 1071, 1073, 1076]), array([1852, 1855, 1846, 1847, 1850]))], [(array([2173, 2174, 2177, 2179, 2182]), array([2411, 2413, 2403, 2404, 2406, 2408]))], [(array([2482, 2484, 2487, 2489, 2479, 2480]), array([2833, 2836, 2827, 2828, 2831])), (array([2500, 2501, 2504, 2506, 2509]), array([2706, 2708, 2711, 2702, 2703]))])



 40%|█████████████████████████████████████████████████████████████████████▌                                                                                                        | 4/10 [00:35<00:53,  8.89s/it]

([(array([86, 87, 90, 92, 95]), array([544, 547, 538, 539, 542]))], [(array([740, 741, 744, 746, 749]), array([1171, 1172, 1174, 1176, 1179, 1181]))], [(array([1192, 1193, 1196, 1198, 1201]), array([1852, 1855, 1846, 1847, 1850]))], [(array([1192, 1193, 1196, 1198, 1201]), array([3160, 3163, 3154, 3155, 3158]))], [(array([2173, 2174, 2177, 2179, 2182]), array([2411, 2413, 2403, 2404, 2406, 2408]))])



 50%|███████████████████████████████████████████████████████████████████████████████████████                                                                                       | 5/10 [00:43<00:43,  8.68s/it]

([(array([86, 87, 90, 92, 95]), array([544, 547, 538, 539, 542]))], [(array([193, 195, 198, 200, 190, 191]), array([871, 874, 865, 866, 869]))], [(array([740, 741, 744, 746, 749]), array([1171, 1172, 1174, 1176, 1179, 1181]))], [(array([847, 849, 852, 854, 844, 845]), array([1498, 1499, 1501, 1503, 1506, 1508]))], [(array([1067, 1068, 1071, 1073, 1076]), array([1852, 1855, 1846, 1847, 1850])), (array([1192, 1193, 1196, 1198, 1201]), array([1725, 1727, 1730, 1721, 1722]))], [(array([2173, 2174, 2177, 2179, 2182]), array([2411, 2413, 2403, 2404, 2406, 2408]))], [(array([2482, 2484, 2487, 2489, 2479, 2480]), array([2833, 2836, 2827, 2828, 2831]))])



 60%|████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                                     | 6/10 [00:51<00:33,  8.38s/it]

([(array([86, 87, 90, 92, 95]), array([544, 547, 538, 539, 542]))], [(array([211, 212, 215, 217, 220]), array([1171, 1172, 1174, 1176, 1179, 1181]))], [(array([740, 741, 744, 746, 749]), array([1171, 1172, 1174, 1176, 1179, 1181]))], [(array([1067, 1068, 1071, 1073, 1076]), array([1852, 1855, 1846, 1847, 1850])), (array([1192, 1193, 1196, 1198, 1201]), array([1852, 1855, 1846, 1847, 1850]))])



 70%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                    | 7/10 [01:00<00:26,  8.81s/it]

([(array([86, 87, 90, 92, 95]), array([544, 547, 538, 539, 542]))], [(array([740, 741, 744, 746, 749]), array([1171, 1172, 1174, 1176, 1179, 1181]))], [(array([847, 849, 852, 854, 844, 845]), array([1498, 1499, 1501, 1503, 1506, 1508]))], [(array([1192, 1193, 1196, 1198, 1201]), array([1852, 1855, 1846, 1847, 1850]))], [(array([2482, 2484, 2487, 2489, 2479, 2480]), array([2833, 2836, 2827, 2828, 2831]))])



 80%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                  | 8/10 [01:10<00:17,  8.96s/it]

([(array([86, 87, 90, 92, 95]), array([544, 547, 538, 539, 542]))], [(array([740, 741, 744, 746, 749]), array([1171, 1172, 1174, 1176, 1179, 1181]))], [(array([847, 849, 852, 854, 844, 845]), array([1498, 1499, 1501, 1503, 1506, 1508]))], [(array([1067, 1068, 1071, 1073, 1076]), array([1852, 1855, 1846, 1847, 1850])), (array([1174, 1176, 1179, 1181, 1171, 1172]), array([1852, 1855, 1846, 1847, 1850])), (array([1192, 1193, 1196, 1198, 1201]), array([1852, 1855, 1846, 1847, 1850]))], [(array([1192, 1193, 1196, 1198, 1201]), array([3160, 3163, 3154, 3155, 3158]))], [(array([2173, 2174, 2177, 2179, 2182]), array([2411, 2413, 2403, 2404, 2406, 2408]))])



 90%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                 | 9/10 [01:19<00:09,  9.07s/it]

([(array([86, 87, 90, 92, 95]), array([544, 547, 538, 539, 542]))], [(array([740, 741, 744, 746, 749]), array([1171, 1172, 1174, 1176, 1179, 1181]))], [(array([847, 849, 852, 854, 844, 845]), array([1498, 1499, 1501, 1503, 1506, 1508]))], [(array([1095, 1096, 1098, 1100, 1103, 1105]), array([1498, 1499, 1501, 1503, 1506, 1508]))], [(array([1067, 1068, 1071, 1073, 1076]), array([1852, 1855, 1846, 1847, 1850])), (array([1192, 1193, 1196, 1198, 1201]), array([1852, 1855, 1846, 1847, 1850]))], [(array([1192, 1193, 1196, 1198, 1201]), array([3160, 3163, 3154, 3155, 3158]))], [(array([2482, 2484, 2487, 2489, 2479, 2480]), array([2833, 2836, 2827, 2828, 2831]))])



100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 10/10 [01:28<00:00,  8.89s/it]

([(array([740, 741, 744, 746, 749]), array([1171, 1172, 1174, 1176, 1179, 1181]))], [(array([847, 849, 852, 854, 844, 845]), array([1498, 1499, 1501, 1503, 1506, 1508]))], [(array([1095, 1096, 1098, 1100, 1103, 1105]), array([1498, 1499, 1501, 1503, 1506, 1508]))], [(array([1192, 1193, 1196, 1198, 1201]), array([1852, 1855, 1846, 1847, 1850]))], [(array([1192, 1193, 1196, 1198, 1201]), array([3160, 3163, 3154, 3155, 3158]))], [(array([1749, 1750, 1752, 1754, 1757, 1759]), array([3133, 3134, 3136, 3138, 3141, 3143]))], [(array([2173, 2174, 2177, 2179, 2182]), array([2411, 2413, 2403, 2404, 2406, 2408]))], [(array([2482, 2484, 2487, 2489, 2479, 2480]), array([2833, 2836, 2827, 2828, 2831]))])
Information succesfully stored in data/rsa_prot_tutorial.parquet
Stacking analysis has succesfully finished!
Function stacking_analysis Took 113.2266 seconds


In [7]:

df_results = 'data/rsa_prot_tutorial.parquet'
df = pd.read_parquet(df_results)

df

atom_index  \
0  [[[740, 741, 744, 746, 749], [1171, 1172, 1174...   
1  [[[86, 87, 90, 92, 95], [544, 547, 538, 539, 5...   
2  [[[86, 87, 90, 92, 95], [544, 547, 538, 539, 5...   
3  [[[86, 87, 90, 92, 95], [544, 547, 538, 539, 5...   
4  [[[86, 87, 90, 92, 95], [544, 547, 538, 539, 5...   
5  [[[86, 87, 90, 92, 95], [544, 547, 538, 539, 5...   
6  [[[86, 87, 90, 92, 95], [544, 547, 538, 539, 5...   
7  [[[86, 87, 90, 92, 95], [544, 547, 538, 539, 5...   
8  [[[86, 87, 90, 92, 95], [544, 547, 538, 539, 5...   
9  [[[740, 741, 744, 746, 749], [1171, 1172, 1174...   

                                           pol_resid  
0                         [[[3, 4], [7, 8], [8, 9]]]  
1  [[[1, 2], [1, 3], [1, 4], [3, 4], [4, 6], [6, ...  
2  [[[1, 2], [3, 4], [3, 5], [4, 6], [7, 8], [8, ...  
3        [[[1, 2], [3, 4], [4, 6], [4, 10], [7, 8]]]  
4  [[[1, 2], [1, 3], [3, 4], [3, 5], [4, 6], [7, ...  
5                 [[[1, 2], [1, 4], [3, 4], [4, 6]]]  
6         [[[1, 2], [3, 4], [3, 5], [4, 6], [8, 9]]]  
7  [[[1, 2], [3, 4], [3, 5], [4, 6], [4, 10], [7,...  
8  [[[1, 2], [3, 4], [3, 5], [4, 5], [4, 6], [4, ...  
9  [[[3, 4], [3, 5], [4, 5], [4, 6], [4, 10], [6,...

In [12]:
df.iloc[0][0]

array([array([array([740, 741, 744, 746, 749]),
              array([1171, 1172, 1174, 1176, 1179, 1181]),
              array([2173, 2174, 2177, 2179, 2182]),
              array([2411, 2413, 2403, 2404, 2406, 2408]),
              array([2482, 2484, 2487, 2489, 2479, 2480]),
              array([2833, 2836, 2827, 2828, 2831]),
              array([2500, 2501, 2504, 2506, 2509]),
              array([2706, 2708, 2711, 2702, 2703])], dtype=object)],
      dtype=object)

In [8]:
sev_ring=RSA(topology, trajectory).find_several_rings_stacked(df_results)

In [9]:
#print the resids of the networ of polymers connected by their stacked rings
print(sev_ring)

[[{3, 4}, {8, 9, 7}], [{1, 2, 3, 4, 6, 8, 9, 10}], [{1, 2}, {3, 4, 5, 6}, {8, 9, 7}], [{1, 2}, {10, 3, 4, 6}, {8, 7}], [{1, 2, 3, 4, 5, 6}, {8, 9, 7}], [{1, 2, 3, 4, 6}], [{1, 2}, {3, 4, 5, 6}, {8, 9}], [{1, 2}, {3, 4, 5, 6, 10}, {8, 7}], [{1, 2}, {3, 4, 5, 6, 10}, {8, 9}], [{3, 4, 5, 6, 10}, {8, 9, 7}]]
